# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterSampler
                                 A QGIS plugin
 This plugin samples raster values at point locations using three methods: exact location, nearest cell value, and mean neighbors value.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-22
        copyright            : (C) 2023 by Amar Begovic
        email                : amarbegovic86@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterSampler class from file RasterSampler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_value_sampler import RasterSampler
    return RasterSampler(iface)
